name = "Kross Hugo"
license = "MIT"
licenselink = "https://github.com/themefisher/kross-hugo/blob/master/LICENSE"
description = "Hugo port of the Themefisherâ€™s Kross Template"
homepage = "https://gethugothemes.com/products/kross-hugo-theme/"
demosite = "https://demo.gethugothemes.com/kross/"
tags = ['landing-page', 'fast', 'light', 'white', 'modern', 'themefisher', 'hugo-theme', 'hugo-templates', 'bootstrap', 'blog', 'responsive', 'clean', 'simple', 'creative', 'contact-form', 'custom-themes', 'mobile', 'minimalistic', 'pages', 'resume', 'portfolio', 'google analytics', 'customizable', 'flexbox', 'presentation', 'product', 'theme', 'typography', 'gethugothemes']
features = ['bootstrap','responsive']
min_version = "0.64.0"

[author]
  name = "Themefisher"
  homepage = "https://themefisher.com/"

[original]
  name = "kross"
  homepage = "https://themefisher.com/products/kross-creative-portfolio-template/"