[hugoVersion]
extended = true
min = "0.109.0"

[[imports]]
path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/components/preloader"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/components/social-share"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/components/cookie-consent"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/components/custom-script"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/components/render-link"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/icons/themify-icons"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/components/valine-comment"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/components/crisp-chat"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/pwa"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/images"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/buttons"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/codepen"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/collapse"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/notice"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/video"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/tabs"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/image"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/gallery"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/table-of-contents"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/youtube-lite"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/vimeo-lite"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/seo-tools/baidu-analytics"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/seo-tools/matomo-analytics"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/seo-tools/plausible-analytics"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/seo-tools/counter-analytics"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/seo-tools/google-tag-manager"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/seo-tools/site-verifications"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/seo-tools/basic-seo"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/gzip-caching"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/adsense"
