---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: exampleSite/data/homepage.yml
  label: Homepage
- type: heading
  label: Blog Post
- type: document
  path: exampleSite/content/blog/_index.md
  label: Blog Page
- type: directory
  path: exampleSite/content/blog
  label: Blog Post
  create: documents
  match: "*"
  exclude: _index.md
  templates:
  - post
- type: heading
  label: Portfolio
- type: document
  path: exampleSite/content/portfolio/_index.md
  label: Portfolio Page
- type: document
  path: exampleSite/data/portfolio.yml
  label: Portfolio Items
- type: heading
  label: About
- type: document
  path: exampleSite/content/about/_index.md
  label: About Page
- type: document
  path: exampleSite/data/about.yml
  label: About Data
- type: heading
  label: Others Page
- type: directory
  path: exampleSite/content/contact
  label: Contact
  create: none
  match: "*"
- type: heading
  label: Configuration
- type: directory
  path: exampleSite
  label: Configuration
  create: all
  match: "*.toml"
  new_doc_ext: toml
upload_dir: exampleSite/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.69.0
