baseURL = "https://culturecat.netlify.app"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Culture Cat"
[[menu.main]]
URL = "about"
name = "About"
weight = 1
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 2
[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 3
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4
[params]
address = "Prague, Czech Republic"
author = "Danica Cortez"
copyright = "Copyright &copy; 2020 a theme by [gethugothemes](https://gethugothemes.com)"
description = "This is meta description"
email = "culturecat.help@gmail.com"
google_analytics_id = ""
home = "Home"
logo = "/images/output-onlinepngtools.png"
phone = "N/A"
social = []
theme_color = "#5271FF"
[params.contact]
enable = false
form_action = "#"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = ""
