baseURL = "https://runi.netlify.com"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Runi Goswami | Design Portfolio"
[[menu.main]]
URL = "blog"
name = "Writing"
url = "https://medium.com/@loonyruni"
weight = 3
[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 1
[params]
address = ""
author = "Runi Goswami"
copyright = "Copyright &copy; 2020 a theme by [gethugothemes](https://gethugothemes.com)"
description = "Runicorn design"
email = "runigoswami@gmail.com"
google_analytics_id = ""
home = "Home"
logo = "images/Logo-Runi-vector.svg"
phone = "+1 571 345 8928"
social = []
theme_color = "#4323C0"
[params.contact]
enable = true
form_action = "#"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = ""
