# default configuration
baseURL = "http://examplesite.com"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Kross | Hugo Portfolio Template"

# css plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"


# menu
[[menu.main]]
URL = "about"
name = "About"
weight = 1

[[menu.main]]
URL = "blog"
name = "Blog"
weight = 2

[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 3

[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4


# default parameters
[params]
home = "Home"
logo = "images/logo.png"
# theme color
theme_color = "#41228e"
# contact info
phone = "+880 2544 658 256"
email = "steve.fruits@email.com"
address = "125/A, CA Commercial Area, California, USA"
# meta description
author = "Johnathan Smith"
description = "This is meta description"
# google analytics
google_analytics_id = "" # Your ID
# copyright
copyright = "Copyright &copy; 2020 a theme by [gethugothemes](https://gethugothemes.com)"


# contact
[params.contact]
enable = true
form_action = "#" # contact form works with : https://formspree.io

# preloader
[params.preloader]
enable = true
preloader = "" # use png, jpg, svg or gif format

# social site
[[params.social]]
icon = "ti-facebook"
URL = "#"

[[params.social]]
icon = "ti-instagram"
URL = "#"

[[params.social]]
icon = "ti-dribbble"
URL = "#"

[[params.social]]
icon = "ti-twitter-alt"
URL = "#"